//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V5.Portal.EmailClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailClient.IEmail")]
    public interface IEmail {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/EmailSend", ReplyAction="http://tempuri.org/IEmail/EmailSendResponse")]
        string EmailSend(string[] Emails, string Title, string Content, string Type);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmailChannel : V5.Portal.EmailClient.IEmail, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailClient : System.ServiceModel.ClientBase<V5.Portal.EmailClient.IEmail>, V5.Portal.EmailClient.IEmail {
        
        public EmailClient() {
        }
        
        public EmailClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string EmailSend(string[] Emails, string Title, string Content, string Type) {
            return base.Channel.EmailSend(Emails, Title, Content, Type);
        }
    }
}
